services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=playground
    volumes:
      # SQL to run when DB is initialised & open for connections. Only runs if
      # the top-level volume is empty.
      - ./setup/seed.sql:/docker-entrypoint-initdb.d/init_seed.sql

  server:
    depends_on:
      - database
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://admin:password@database:5432/playground
      - JWT_SECRET=secret
    volumes:
      # Source files for hot-reloading.
      - ../main.go:/server-local/main.go
      - ../internal:/server-local/internal

  client:
    restart: on-failure
    depends_on:
      - server
    build:
      context: ../
      dockerfile: docker/client.Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      - SERVER_URL=http://server:8080
    volumes:
      # Source files for hot-reloading.
      # NOTE: Generated types are shared within the .svelte-kit folder.
      - ../client/.svelte-kit:/client-local/.svelte-kit
      - ../client/src:/client-local/src
